const mockAuctions=[
 {id:1,title:"MacBook Pro M2 16GB",category:"Tecnología",currentBid:850000,minimumIncrement:10000,endTime:"00:45:10",status:"Activa",img:"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80"},
 {id:2,title:"Silla Gamer Noblechairs",category:"Hogar y Oficina",currentBid:120000,minimumIncrement:5000,endTime:"02:15:00",status:"Activa",img:"https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=900&q=80"},
 {id:3,title:"Monitor UltraWide LG 34’",category:"Tecnología",currentBid:340000,minimumIncrement:15000,endTime:"00:00:30",status:"Por terminar",img:"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80"}
];
document.addEventListener("DOMContentLoaded",()=>{renderAuctions(mockAuctions);configureNavigation();configureVisualControls();showView(getViewFromHash(),false)});
function configureNavigation(){document.querySelectorAll("[data-view]").forEach(link=>link.addEventListener("click",event=>{event.preventDefault();history.replaceState(null,"",`#${link.dataset.view}`);showView(link.dataset.view)}));window.addEventListener("hashchange",()=>showView(getViewFromHash(),false))}
function getViewFromHash(){const view=location.hash.slice(1);return["catalog","activities","wallet"].includes(view)?view:"catalog"}
function showView(name,scroll=true){document.querySelectorAll(".app-view").forEach(view=>view.classList.toggle("active",view.dataset.page===name));document.querySelectorAll(".main-nav [data-view]").forEach(link=>link.classList.toggle("active",link.dataset.view===name));const menu=document.getElementById("navbarNav");if(menu?.classList.contains("show")&&window.bootstrap)bootstrap.Collapse.getOrCreateInstance(menu).hide();if(scroll)window.scrollTo({top:0,behavior:"smooth"})}
function configureVisualControls(){document.querySelectorAll(".amount-options button").forEach(button=>button.addEventListener("click",event=>{event.preventDefault();document.querySelectorAll(".amount-options button").forEach(item=>item.classList.remove("selected"));button.classList.add("selected");const input=document.getElementById("deposit-amount");input.value=button.dataset.amount;if(!button.dataset.amount)input.focus()}));document.querySelectorAll(".tabs").forEach(group=>group.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{group.querySelectorAll("button").forEach(tab=>tab.classList.remove("active"));button.classList.add("active")})))}
function renderAuctions(auctions){const container=document.getElementById("auctions-container");container.innerHTML="";auctions.forEach(auction=>{const ending=auction.status==="Por terminar",column=document.createElement("div");column.className="col-12 col-md-6 col-xl-4";column.innerHTML=`<article class="auction-card"><div class="auction-image-wrap"><img src="${auction.img}" alt="${auction.title}"><span class="auction-status ${ending?"ending":""}">${ending?"Por terminar":"▣ Activa"}</span><button class="favorite-button" aria-label="Agregar a favoritos">♡</button><span class="time-badge ${ending?"ending":""}">◴ ${auction.endTime}</span></div><div class="auction-body"><h2>${auction.title}</h2><span class="category-badge">${auction.category}</span><div class="auction-values"><div><span>Oferta actual</span><strong class="current-price">${money(auction.currentBid)}</strong></div><div class="text-end"><span>Incremento mínimo</span><strong>${money(auction.minimumIncrement)}</strong></div></div><button class="bid-button" onclick="enterLiveRoom()">⚒&nbsp; Ingresar a pujar</button></div></article>`;container.appendChild(column)})}
function money(value){return`$${value.toLocaleString("es-AR")}`}
function enterLiveRoom(){alert("La sala de pujas se integrará en una próxima etapa.")}
