// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.API.Data;

#nullable disable

namespace SubastaYa.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902034415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("SubastaYa.API.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatalleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = new byte[] { 1 }
                        },
                        new
                        {
                            Id = 2,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = new byte[] { 2 }
                        },
                        new
                        {
                            Id = 3,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = new byte[] { 3 }
                        },
                        new
                        {
                            Id = 4,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = new byte[] { 4 }
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "tech.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "col.png"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "ind.png"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = "veh.png"
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompradorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2025, 1, 1, 12, 10, 0, 0, DateTimeKind.Utc),
                            Monto = 35000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2025, 1, 1, 12, 20, 0, 0, DateTimeKind.Utc),
                            Monto = 45000m,
                            SubastaId = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.ToTable("Subastas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Usada",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2030, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 30000m,
                            Titulo = "MacBook Pro",
                            UrlImagen = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600",
                            VendedorId = 1,
                            Version = new byte[] { 1 }
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Colección",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2030, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 10000m,
                            Titulo = "Reloj Antiguo",
                            UrlImagen = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600",
                            VendedorId = 1,
                            Version = new byte[] { 2 }
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Nuevas",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2031, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2031, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 50000m,
                            Titulo = "Zapatillas Jordan",
                            UrlImagen = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600",
                            VendedorId = 1,
                            Version = new byte[] { 3 }
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "24 pulgadas",
                            Estado = "FINALIZADA",
                            FechaFin = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 15000m,
                            Titulo = "Monitor LG",
                            UrlImagen = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600",
                            VendedorId = 1,
                            Version = new byte[] { 4 }
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "Playera",
                            Estado = "DESIERTA",
                            FechaFin = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 80000m,
                            Titulo = "Bicicleta",
                            UrlImagen = "https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=600",
                            VendedorId = 1,
                            Version = new byte[] { 5 }
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BilleteraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransaccionesLedger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 150000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 3,
                            Fecha = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 200000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 4,
                            Fecha = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 500m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 2,
                            Fecha = new DateTime(2025, 1, 1, 12, 20, 0, 0, DateTimeKind.Utc),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = "RETENCION"
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vendedor",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador 1",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador 2",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Sin Fondos",
                            PasswordHash = "hash123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
