// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.API.Data;

#nullable disable

namespace SubastaYa.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915220855_HardenAuctionSettlementConcurrency")]
    partial class HardenAuctionSettlementConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.API.Models.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaveIdempotencia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("UX_AuditoriaLogs_ClaveIdempotencia")
                        .HasFilter("[ClaveIdempotencia] IS NOT NULL");

                    b.HasIndex("SubastaId", "FechaUtc");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras", null, t =>
                        {
                            t.HasCheckConstraint("CK_Billeteras_RetenidoNoSuperaTotal", "[SaldoRetenido] <= [SaldoTotal]");

                            t.HasCheckConstraint("CK_Billeteras_SaldoDisponibleConsistente", "[SaldoDisponible] = [SaldoTotal] - [SaldoRetenido]");

                            t.HasCheckConstraint("CK_Billeteras_SaldosNoNegativos", "[SaldoTotal] >= 0 AND [SaldoRetenido] >= 0 AND [SaldoDisponible] >= 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.LiquidacionSubasta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaAdjudicacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaLiquidacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ImporteFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PujaGanadoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("PujaGanadoraId")
                        .IsUnique()
                        .HasDatabaseName("UX_LiquidacionesSubasta_PujaGanadoraId");

                    b.HasIndex("SubastaId")
                        .IsUnique()
                        .HasDatabaseName("UX_LiquidacionesSubasta_SubastaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("LiquidacionesSubasta", null, t =>
                        {
                            t.HasCheckConstraint("CK_LiquidacionesSubasta_ImporteFinalPositivo", "[ImporteFinal] > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsGanadora")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubastaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Pujas_SubastaId_Ganadora")
                        .HasFilter("[EsGanadora] = 1");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SubastaId", "FechaUtc");

                    b.ToTable("Pujas");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("FechaFinUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaInicioUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFinUtc");

                    b.HasIndex("PrecioActual");

                    b.HasIndex("VendedorId");

                    b.HasIndex("Estado", "FechaFinUtc", "Id")
                        .HasDatabaseName("IX_Subastas_Estado_FechaFinUtc_Id");

                    b.HasIndex("Estado", "FechaInicioUtc", "Id")
                        .HasDatabaseName("IX_Subastas_Estado_FechaInicioUtc_Id");

                    b.ToTable("Subastas", (string)null);
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BilleteraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaveIdempotencia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LiquidacionSubastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("ClaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("UX_TransaccionesLedger_ClaveIdempotencia")
                        .HasFilter("[ClaveIdempotencia] IS NOT NULL");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("LiquidacionSubastaId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("UX_TransaccionesLedger_LiquidacionSubastaId_Tipo")
                        .HasFilter("[LiquidacionSubastaId] IS NOT NULL");

                    b.ToTable("TransaccionesLedger", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransaccionesLedger_MontoPositivo", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SubastaYa.API.Models.AuditoriaLog", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.API.Models.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.LiquidacionSubasta", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Puja", "PujaGanadora")
                        .WithMany()
                        .HasForeignKey("PujaGanadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithOne("Liquidacion")
                        .HasForeignKey("SubastaYa.API.Models.LiquidacionSubasta", "SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("PujaGanadora");

                    b.Navigation("Subasta");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.LiquidacionSubasta", "LiquidacionSubasta")
                        .WithMany("Movimientos")
                        .HasForeignKey("LiquidacionSubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("LiquidacionSubasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.LiquidacionSubasta", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Navigation("Billetera");
                });
#pragma warning restore 612, 618
        }
    }
}
